package enums;

/*
 * Classe baseada no resultado da API: https://economia.awesomeapi.com.br/json/available
 */
public enum EnumCoinCombinations {
  //region Combinations
  // region A
  ARS_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.ARS, EnumCoin.BRL)),
  AED_USD(EnumCoin.descriptionFromCombinations(EnumCoin.AED, EnumCoin.USD)),
  ARS_USD(EnumCoin.descriptionFromCombinations(EnumCoin.ARS, EnumCoin.USD)),
  AUD_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.AUD, EnumCoin.BRL)),
  AUD_USD(EnumCoin.descriptionFromCombinations(EnumCoin.AUD, EnumCoin.USD)),
  ARS_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.ARS, EnumCoin.EUR)),
  AUD_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.AUD, EnumCoin.EUR)),
  AED_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.AED, EnumCoin.BRL)),
  AFN_USD(EnumCoin.descriptionFromCombinations(EnumCoin.AFN, EnumCoin.USD)),
  //endregion
  //region B
  BOB_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.BOB, EnumCoin.BRL)),
  BHD_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.BHD, EnumCoin.EUR)),
  RUB_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.RUB, EnumCoin.BRL)),
  BOB_USD(EnumCoin.descriptionFromCombinations(EnumCoin.BOB, EnumCoin.USD)),
  BTC_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.BTC, EnumCoin.BRL)),
  BTC_USD(EnumCoin.descriptionFromCombinations(EnumCoin.BTC, EnumCoin.USD)),
  BRL_USD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.USD)),
  BRL_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.EUR)),
  BTC_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.BTC, EnumCoin.EUR)),
  BYN_USD(EnumCoin.descriptionFromCombinations(EnumCoin.BYN, EnumCoin.USD)),
  BRL_ARS(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.ARS)),
  BRL_AUD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.AUD)),
  BRL_CAD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.CAD)),
  BRL_CHF(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.CHF)),
  BRL_CLP(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.CLP)),
  BRL_DKK(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.DKK)),
  BRL_HKD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.HKD)),
  BRL_JPY(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.JPY)),
  BRL_MXN(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.MXN)),
  BRL_SGD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.SGD)),
  BRL_AED(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.AED)),
  BRL_BBD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.BBD)),
  BRL_BHD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.BHD)),
  BRL_CNY(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.CNY)),
  BRL_CZK(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.CZK)),
  BRL_EGP(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.EGP)),
  BRL_GBP(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.GBP)),
  BRL_HUF(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.HUF)),
  BRL_IDR(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.IDR)),
  BRL_ILS(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.ILS)),
  BRL_INR(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.INR)),
  BRL_ISK(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.ISK)),
  BRL_JMD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.JMD)),
  BRL_JOD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.JOD)),
  BRL_KES(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.KES)),
  BRL_KRW(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.KRW)),
  BRL_LBP(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.LBP)),
  BRL_LKR(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.LKR)),
  BRL_MAD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.MAD)),
  BRL_MYR(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.MYR)),
  BRL_NAD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.NAD)),
  BRL_NOK(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.NOK)),
  BRL_NPR(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.NPR)),
  BRL_NZD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.NZD)),
  BRL_OMR(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.OMR)),
  BRL_PAB(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.PAB)),
  BRL_PHP(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.PHP)),
  BRL_PKR(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.PKR)),
  BRL_PLN(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.PLN)),
  BRL_QAR(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.QAR)),
  BRL_RON(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.RON)),
  BRL_RUB(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.RUB)),
  BRL_SAR(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.SAR)),
  BRL_SEK(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.SEK)),
  BRL_THB(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.THB)),
  BRL_TRY(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.TRY)),
  BRL_VEF(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.VEF)),
  BRL_XAF(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.XAF)),
  BRL_XCD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.XCD)),
  BRL_XOF(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.XOF)),
  BRL_ZAR(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.ZAR)),
  BRL_TWD(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.TWD)),
  BRL_PYG(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.PYG)),
  BRL_UYU(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.UYU)),
  BRL_COP(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.COP)),
  BRL_PEN(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.PEN)),
  BRL_BOB(EnumCoin.descriptionFromCombinations(EnumCoin.BRL, EnumCoin.BOB)),
  BYN_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.BYN, EnumCoin.EUR)),
  //endregion
  // region C
  CAD_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.CAD, EnumCoin.EUR)),
  CAD_USD(EnumCoin.descriptionFromCombinations(EnumCoin.CAD, EnumCoin.USD)),
  CAD_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.CAD, EnumCoin.BRL)),
  CHF_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.CHF, EnumCoin.BRL)),
  CNY_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.CNY, EnumCoin.BRL)),
  CHF_USD(EnumCoin.descriptionFromCombinations(EnumCoin.CHF, EnumCoin.USD)),
  CNY_USD(EnumCoin.descriptionFromCombinations(EnumCoin.CNY, EnumCoin.USD)),
  COP_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.COP, EnumCoin.BRL)),
  CNY_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.CNY, EnumCoin.EUR)),
  CLP_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.CLP, EnumCoin.BRL)),
  CHF_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.CHF, EnumCoin.EUR)),
  CLP_USD(EnumCoin.descriptionFromCombinations(EnumCoin.CLP, EnumCoin.USD)),
  COP_USD(EnumCoin.descriptionFromCombinations(EnumCoin.COP, EnumCoin.USD)),
  //endregion
  // region D
  DKK_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.DKK, EnumCoin.BRL)),
  DOGE_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.DOGE, EnumCoin.BRL)),
  DKK_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.DKK, EnumCoin.EUR)),
  DOGE_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.DOGE, EnumCoin.EUR)),
  DOGE_USD(EnumCoin.descriptionFromCombinations(EnumCoin.DOGE, EnumCoin.USD)),
  DKK_USD(EnumCoin.descriptionFromCombinations(EnumCoin.DKK, EnumCoin.USD)),
  //endregion
  // region E
  EUR_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.BRL)),
  EGP_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.EGP, EnumCoin.EUR)),
  EUR_GBP(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.GBP)),
  EGP_USD(EnumCoin.descriptionFromCombinations(EnumCoin.EGP, EnumCoin.USD)),
  ETH_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.ETH, EnumCoin.BRL)),
  ETH_USD(EnumCoin.descriptionFromCombinations(EnumCoin.ETH, EnumCoin.USD)),
  ETH_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.ETH, EnumCoin.EUR)),
  EUR_USD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.USD)),
  EUR_JPY(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.JPY)),
  EUR_CHF(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.CHF)),
  EUR_AUD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.AUD)),
  EUR_CAD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.CAD)),
  EUR_NOK(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.NOK)),
  EUR_DKK(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.DKK)),
  EUR_PLN(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.PLN)),
  EUR_NZD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.NZD)),
  EUR_SEK(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.SEK)),
  EUR_ILS(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.ILS)),
  EUR_TRY(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.TRY)),
  EUR_THB(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.THB)),
  EUR_ZAR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.ZAR)),
  EUR_MXN(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.MXN)),
  EUR_SGD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.SGD)),
  EUR_HUF(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.HUF)),
  EUR_HKD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.HKD)),
  EUR_CZK(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.CZK)),
  EUR_KRW(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.KRW)),
  EUR_AED(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.AED)),
  EUR_AFN(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.AFN)),
  EUR_ALL(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.ALL)),
  EUR_ANG(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.ANG)),
  EUR_ARS(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.ARS)),
  EUR_BAM(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.BAM)),
  EUR_BBD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.BBD)),
  EUR_BDT(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.BDT)),
  EUR_BGN(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.BGN)),
  EUR_BHD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.BHD)),
  EUR_BIF(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.BIF)),
  EUR_BND(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.BND)),
  EUR_BOB(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.BOB)),
  EUR_BSD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.BSD)),
  EUR_BWP(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.BWP)),
  EUR_BYN(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.BYN)),
  EUR_BZD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.BZD)),
  EUR_CLP(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.CLP)),
  EUR_CNY(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.CNY)),
  EUR_COP(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.COP)),
  EUR_CRC(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.CRC)),
  EUR_CUP(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.CUP)),
  EUR_CVE(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.CVE)),
  EUR_DJF(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.DJF)),
  EUR_DOP(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.DOP)),
  EUR_DZD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.DZD)),
  EUR_EGP(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.EGP)),
  EUR_ETB(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.ETB)),
  EUR_FJD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.FJD)),
  EUR_GHS(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.GHS)),
  EUR_GMD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.GMD)),
  EUR_GNF(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.GNF)),
  EUR_GTQ(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.GTQ)),
  EUR_HNL(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.HNL)),
  EUR_HRK(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.HRK)),
  EUR_HTG(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.HTG)),
  EUR_IDR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.IDR)),
  EUR_INR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.INR)),
  EUR_IQD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.IQD)),
  EUR_IRR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.IRR)),
  EUR_ISK(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.ISK)),
  EUR_JMD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.JMD)),
  EUR_JOD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.JOD)),
  EUR_KES(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.KES)),
  EUR_KHR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.KHR)),
  EUR_KWD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.KWD)),
  EUR_KYD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.KYD)),
  EUR_KZT(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.KZT)),
  EUR_LAK(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.LAK)),
  EUR_LBP(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.LBP)),
  EUR_LKR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.LKR)),
  EUR_LSL(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.LSL)),
  EUR_LYD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.LYD)),
  EUR_MAD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.MAD)),
  EUR_MDL(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.MDL)),
  EUR_MGA(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.MGA)),
  EUR_MKD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.MKD)),
  EUR_MMK(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.MMK)),
  EUR_MOP(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.MOP)),
  EUR_MRO(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.MRO)),
  EUR_MUR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.MUR)),
  EUR_MWK(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.MWK)),
  EUR_MYR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.MYR)),
  EUR_NAD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.NAD)),
  EUR_NGN(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.NGN)),
  EUR_NIO(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.NIO)),
  EUR_NPR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.NPR)),
  EUR_OMR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.OMR)),
  EUR_PAB(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.PAB)),
  EUR_PEN(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.PEN)),
  EUR_PGK(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.PGK)),
  EUR_PHP(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.PHP)),
  EUR_PKR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.PKR)),
  EUR_PYG(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.PYG)),
  EUR_QAR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.QAR)),
  EUR_RON(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.RON)),
  EUR_RSD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.RSD)),
  EUR_RWF(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.RWF)),
  EUR_SAR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.SAR)),
  EUR_SCR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.SCR)),
  EUR_SDG(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.SDG)),
  AED_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.EUR)),
  EUR_SDR(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.SDR)),
  EUR_SOS(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.SOS)),
  EUR_STD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.STD)),
  EUR_SVC(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.SVC)),
  EUR_SYP(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.SYP)),
  EUR_SZL(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.SZL)),
  EUR_TND(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.TND)),
  EUR_TTD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.TTD)),
  EUR_TWD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.TWD)),
  EUR_TZS(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.TZS)),
  EUR_UAH(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.UAH)),
  EUR_UGX(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.UGX)),
  EUR_UYU(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.UYU)),
  EUR_UZS(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.UZS)),
  EUR_VEF(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.VEF)),
  EUR_VND(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.VND)),
  EUR_XAF(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.XAF)),
  EUR_XOF(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.XOF)),
  EUR_XPF(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.XPF)),
  EUR_ZMK(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.ZMK)),
  EUR_XCD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.XCD)),
  EUR_MZN(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.MZN)),
  EUR_AZN(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.AZN)),
  EUR_AMD(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.AMD)),
  EUR_TJS(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.TJS)),
  EUR_RUB(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.RUB)),
  EUR_GEL(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.GEL)),
  EUR_AOA(EnumCoin.descriptionFromCombinations(EnumCoin.EUR, EnumCoin.AOA)),
  //endregion
  // region F
  FJD_USD(EnumCoin.descriptionFromCombinations(EnumCoin.FJD, EnumCoin.USD)),
  //endregion
  // region G
  GBP_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.GBP, EnumCoin.BRL)),
  GEL_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.GEL, EnumCoin.EUR)),
  GHS_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.GHS, EnumCoin.EUR)),
  GBP_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.GBP, EnumCoin.EUR)),
  GBP_USD(EnumCoin.descriptionFromCombinations(EnumCoin.GBP, EnumCoin.USD)),
  GHS_USD(EnumCoin.descriptionFromCombinations(EnumCoin.GHS, EnumCoin.USD)),
  //endregion
  // region H
  HKD_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.HKD, EnumCoin.BRL)),
  HKD_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.HKD, EnumCoin.EUR)),
  HKD_USD(EnumCoin.descriptionFromCombinations(EnumCoin.HKD, EnumCoin.USD)),
  HUF_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.HUF, EnumCoin.EUR)),
  HUF_USD(EnumCoin.descriptionFromCombinations(EnumCoin.HUF, EnumCoin.USD)),
  //endregion
  // region I
  IDR_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.IDR, EnumCoin.EUR)),
  IDR_USD(EnumCoin.descriptionFromCombinations(EnumCoin.IDR, EnumCoin.USD)),
  ILS_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.ILS, EnumCoin.BRL)),
  ILS_USD(EnumCoin.descriptionFromCombinations(EnumCoin.ILS, EnumCoin.USD)),
  ILS_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.ILS, EnumCoin.EUR)),
  INR_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.INR, EnumCoin.EUR)),
  INR_USD(EnumCoin.descriptionFromCombinations(EnumCoin.INR, EnumCoin.USD)),
  INR_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.INR, EnumCoin.BRL)),
  IRR_USD(EnumCoin.descriptionFromCombinations(EnumCoin.IRR, EnumCoin.USD)),
  IQD_USD(EnumCoin.descriptionFromCombinations(EnumCoin.IQD, EnumCoin.USD)),
  //endregion
  // region J
  JOD_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.JOD, EnumCoin.EUR)),
  JOD_USD(EnumCoin.descriptionFromCombinations(EnumCoin.JOD, EnumCoin.USD)),
  JPY_USD(EnumCoin.descriptionFromCombinations(EnumCoin.JPY, EnumCoin.USD)),
  JPY_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.JPY, EnumCoin.BRL)),
  JPY_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.JPY, EnumCoin.EUR)),
  //endregion
  // region K
  KYD_USD(EnumCoin.descriptionFromCombinations(EnumCoin.KYD, EnumCoin.USD)),
  KRW_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.KRW, EnumCoin.EUR)),
  KRW_USD(EnumCoin.descriptionFromCombinations(EnumCoin.KRW, EnumCoin.USD)),
  KWD_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.KWD, EnumCoin.EUR)),
  KWD_USD(EnumCoin.descriptionFromCombinations(EnumCoin.KWD, EnumCoin.USD)),
  //endregion
  // region L
  LTC_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.LTC, EnumCoin.BRL)),
  LTC_USD(EnumCoin.descriptionFromCombinations(EnumCoin.LTC, EnumCoin.USD)),
  LTC_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.LTC, EnumCoin.EUR)),
  //endregion
  // region M
  MAD_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.MAD, EnumCoin.EUR)),
  MXN_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.MXN, EnumCoin.BRL)),
  MXN_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.MXN, EnumCoin.EUR)),
  MXN_USD(EnumCoin.descriptionFromCombinations(EnumCoin.MXN, EnumCoin.USD)),
  MYR_USD(EnumCoin.descriptionFromCombinations(EnumCoin.MYR, EnumCoin.USD)),
  //endregion
  // region N
  NIO_USD(EnumCoin.descriptionFromCombinations(EnumCoin.BOB, EnumCoin.USD)),
  NOK_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.NOK, EnumCoin.BRL)),
  NOK_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.NOK, EnumCoin.EUR)),
  NOK_USD(EnumCoin.descriptionFromCombinations(EnumCoin.NOK, EnumCoin.USD)),
  NZD_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.NZD, EnumCoin.EUR)),
  NZD_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.NZD, EnumCoin.BRL)),
  NZD_USD(EnumCoin.descriptionFromCombinations(EnumCoin.NZD, EnumCoin.USD)),
  //endregion
  // region P
  PEN_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.PEN, EnumCoin.BRL)),
  PYG_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.PYG, EnumCoin.BRL)),
  PLN_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.PLN, EnumCoin.BRL)),
  PLN_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.PLN, EnumCoin.EUR)),
  PEN_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.PEN, EnumCoin.EUR)),
  PLN_USD(EnumCoin.descriptionFromCombinations(EnumCoin.PLN, EnumCoin.USD)),
  PEN_USD(EnumCoin.descriptionFromCombinations(EnumCoin.PEN, EnumCoin.USD)),
  PHP_USD(EnumCoin.descriptionFromCombinations(EnumCoin.PHP, EnumCoin.USD)),
  PYG_USD(EnumCoin.descriptionFromCombinations(EnumCoin.PYG, EnumCoin.USD)),
  //endregion
  // region R
  RUB_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.RUB, EnumCoin.EUR)),
  RUB_USD(EnumCoin.descriptionFromCombinations(EnumCoin.RUB, EnumCoin.USD)),
  //endregion
  // region S
  SAR_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.SAR, EnumCoin.BRL)),
  SAR_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.SAR, EnumCoin.EUR)),
  SAR_USD(EnumCoin.descriptionFromCombinations(EnumCoin.SAR, EnumCoin.USD)),
  SEK_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.SEK, EnumCoin.BRL)),
  SEK_USD(EnumCoin.descriptionFromCombinations(EnumCoin.SEK, EnumCoin.USD)),
  SGD_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.SGD, EnumCoin.BRL)),
  SEK_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.SEK, EnumCoin.EUR)),
  SGD_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.SGD, EnumCoin.EUR)),
  SGD_USD(EnumCoin.descriptionFromCombinations(EnumCoin.SGD, EnumCoin.USD)),
  SYP_USD(EnumCoin.descriptionFromCombinations(EnumCoin.SYP, EnumCoin.USD)),
  //endregion
  // region T
  THB_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.THB, EnumCoin.BRL)),
  THB_USD(EnumCoin.descriptionFromCombinations(EnumCoin.THB, EnumCoin.USD)),
  TRY_USD(EnumCoin.descriptionFromCombinations(EnumCoin.TRY, EnumCoin.USD)),
  TRY_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.TRY, EnumCoin.BRL)),
  TRY_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.TRY, EnumCoin.EUR)),
  TWD_USD(EnumCoin.descriptionFromCombinations(EnumCoin.TWD, EnumCoin.USD)),
  TWD_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.TWD, EnumCoin.BRL)),
  TWD_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.TWD, EnumCoin.EUR)),

  //endregion
  // region U
  USD_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.BRL)),
  USD_BRLT(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.BRLT)),
  UYU_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.UYU, EnumCoin.BRL)),
  UAH_USD(EnumCoin.descriptionFromCombinations(EnumCoin.UAH, EnumCoin.USD)),
  USD_NGNI(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.NGNI)),
  USD_ZWL(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.ZWL)),
  UYU_USD(EnumCoin.descriptionFromCombinations(EnumCoin.UYU, EnumCoin.USD)),
  USD_CAD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.CAD)),
  USD_JPY(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.JPY)),
  USD_CHF(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.CHF)),
  USD_MZN(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MZN)),
  USD_RUB(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.RUB)),
  USD_TRY(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.TRY)),
  USD_MXN(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MXN)),
  USD_PLN(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.PLN)),
  USD_SEK(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.SEK)),
  USD_SGD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.SGD)),
  USD_ZAR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.ZAR)),
  USD_DKK(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.DKK)),
  USD_NOK(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.NOK)),
  USD_ILS(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.ILS)),
  USD_HUF(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.HUF)),
  USD_CZK(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.CZK)),
  USD_THB(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.THB)),
  USD_AED(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.AED)),
  USD_JOD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.JOD)),
  USD_KWD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.KWD)),
  USD_HKD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.HKD)),
  USD_SAR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.SAR)),
  USD_INR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.INR)),
  USD_KRW(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.KRW)),
  USD_ALL(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.ALL)),
  USD_AMD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.AMD)),
  USD_ANG(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.ANG)),
  USD_ARS(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.ARS)),
  USD_AUD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.AUD)),
  USD_BBD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.BBD)),
  USD_BDT(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.BDT)),
  USD_BGN(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.BGN)),
  USD_BHD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.BHD)),
  USD_BIF(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.BIF)),
  USD_BND(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.BND)),
  USD_BOB(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.BOB)),
  USD_BSD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.BSD)),
  USD_BWP(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.BWP)),
  USD_BZD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.BZD)),
  USD_CLP(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.CLP)),
  USD_CNY(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.CNY)),
  USD_COP(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.COP)),
  USD_CRC(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.CRC)),
  USD_CUP(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.CUP)),
  USD_DJF(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.DJF)),
  USD_DOP(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.DOP)),
  USD_DZD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.DZD)),
  USD_EGP(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.EGP)),
  USD_ETB(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.ETB)),
  USD_FJD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.FJD)),
  USD_GBP(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.GBP)),
  USD_GEL(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.GEL)),
  USD_GHS(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.GHS)),
  USD_GMD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.GMD)),
  USD_GNF(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.GNF)),
  USD_GTQ(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.GTQ)),
  USD_HNL(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.HNL)),
  USD_HRK(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.HRK)),
  USD_HTG(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.HTG)),
  USD_IDR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.IDR)),
  USD_IQD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.IQD)),
  USD_IRR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.IRR)),
  USD_ISK(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.ISK)),
  USD_JMD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.JMD)),
  USD_KES(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.KES)),
  USD_KHR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.KHR)),
  USD_KMF(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.KMF)),
  USD_KZT(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.KZT)),
  USD_LAK(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.LAK)),
  USD_LBP(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.LBP)),
  USD_LKR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.LKR)),
  USD_LSL(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.LSL)),
  USD_LYD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.LYD)),
  USD_MAD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MAD)),
  USD_MDL(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MDL)),
  USD_MGA(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MGA)),
  USD_MKD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MKD)),
  USD_MMK(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MMK)),
  USD_MOP(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MOP)),
  USD_MRO(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MRO)),
  USD_MUR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MUR)),
  USD_MVR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MVR)),
  USD_MWK(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MWK)),
  USD_MYR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MYR)),
  USD_NAD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.NAD)),
  USD_NGN(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.NGN)),
  USD_NIO(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.NIO)),
  USD_NPR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.NPR)),
  USD_NZD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.NZD)),
  USD_OMR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.OMR)),
  USD_PAB(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.PAB)),
  USD_PEN(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.PEN)),
  USD_PGK(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.PGK)),
  USD_PHP(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.PHP)),
  USD_PKR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.PKR)),
  USD_PYG(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.PYG)),
  USD_QAR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.QAR)),
  USD_RON(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.RON)),
  USD_RSD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.RSD)),
  USD_RWF(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.RWF)),
  USD_SCR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.SCR)),
  USD_SDG(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.SDG)),
  USD_SOS(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.SOS)),
  USD_STD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.STD)),
  USD_SVC(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.SVC)),
  USD_SYP(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.SYP)),
  USD_SZL(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.SZL)),
  USD_TND(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.TND)),
  USD_TTD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.TTD)),
  USD_TWD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.TWD)),
  USD_TZS(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.TZS)),
  USD_UAH(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.UAH)),
  USD_UGX(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.UGX)),
  USD_UYU(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.UYU)),
  USD_UZS(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.UZS)),
  USD_VEF(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.VEF)),
  USD_VND(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.VND)),
  USD_VUV(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.VUV)),
  USD_XAF(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.XAF)),
  USD_XCD(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.XCD)),
  USD_XOF(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.XOF)),
  USD_XPF(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.XPF)),
  USD_YER(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.YER)),
  USD_ZMK(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.ZMK)),
  USD_BYN(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.BYN)),
  USD_AZN(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.AZN)),
  USD_CNH(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.CNH)),
  USD_KGS(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.KGS)),
  USD_TJS(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.TJS)),
  USD_AOA(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.AOA)),
  USD_TMT(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.TMT)),
  USD_MNT(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.MNT)),
  USD_AFN(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.AFN)),

  USD_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.USD, EnumCoin.EUR)),
  //endregion
  // region V
  VEF_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.VEF, EnumCoin.BRL)),
  VEF_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.VEF, EnumCoin.EUR)),
  VEF_USD(EnumCoin.descriptionFromCombinations(EnumCoin.VEF, EnumCoin.USD)),
  VND_USD(EnumCoin.descriptionFromCombinations(EnumCoin.VND, EnumCoin.USD)),
  //endregion
  // region X
  XAGG_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.XAGG, EnumCoin.EUR)),
  XAGG_USD(EnumCoin.descriptionFromCombinations(EnumCoin.XAGG, EnumCoin.USD)),
  XBR_USD(EnumCoin.descriptionFromCombinations(EnumCoin.XBR, EnumCoin.USD)),
  XRP_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.XRP, EnumCoin.BRL)),
  XRP_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.XRP, EnumCoin.EUR)),
  XRP_USD(EnumCoin.descriptionFromCombinations(EnumCoin.XRP, EnumCoin.USD)),
  //endregion
  // region Z
  ZAR_EUR(EnumCoin.descriptionFromCombinations(EnumCoin.ZAR, EnumCoin.EUR)),
  ZAR_BRL(EnumCoin.descriptionFromCombinations(EnumCoin.ZAR, EnumCoin.BRL)),
  ZAR_USD(EnumCoin.descriptionFromCombinations(EnumCoin.ZAR, EnumCoin.USD));
  //endregion
  //endregion

  public final String description;

  EnumCoinCombinations(String description) {
    this.description = description;
  }

  @Override
  public String toString() {
    return this.name().replace("_", "-");
  }
}
